### ISSUE TITLE
Error running program

### ISSUE THREAD

**Issue by immuhammadadil** [VAIBHAV-2303/VideoStabilization#1]
adil@adil-HP-Pavilion-Notebook:/media/adil/Ubuntu 18.04 LTS amd64/VideoStabilization-master$ python3 preproc.py shakey2.mp4
Traceback (most recent call last):
  File "preproc.py", line 6, in <module>
    sift = cv2.xfeatures2d.SIFT_create(200)
cv2.error: OpenCV(4.1.0) /io/opencv_contrib/modules/xfeatures2d/src/sift.cpp:1207: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'create'

**Comment by Debiprasad-1** [comment]
in stabilize.py one DispThresh = int(sys.argv[1]) code is there what i will put. means the second execution is python3 stabilize.py (some number we have to mention.). what is that displace Threshold ?

#  python3 stabilize.py  Number?

**Comment by zhengziqiang** [comment]
@Debiprasad-1 I tried 100, and it worked for me.

**Comment by VAIBHAV-2303** [comment]
@Debiprasad-1 and @zhengziqiang  The DispThresh is an integer value representing the maximum difference(in pixels) in the smoothened trajectory and the actual trajectory. It will generally be around 30. I have also updated the docs accordingly.

**Comment by VAIBHAV-2303** [comment]
@immuhammadadil Please install python-opencv-contrib to be able to extract sift features.
I will be closing this issue.
