### ISSUE TITLE
Displacement_threshold_pixels

### ISSUE THREAD

**Issue by echo-gui** [VAIBHAV-2303/VideoStabilization#2]
Hi, your project seems very interesting, and I am wondering how to get the _Displacement_threshold_pixels_ file?

**Comment by chestnut111** [comment]
Hi, your project seems very interesting, and I am wondering how to get the Displacement_threshold_pixels file?

**Comment by VAIBHAV-2303** [comment]
I'm not sure what is it you mean by the Dispacement_threshold_pixels file, can you please elaborate?

**Comment by Wanrui-account** [comment]
> I'm not sure what is it you mean by the Dispacement_threshold_pixels file, can you please elaborate?
hi，thanks for your work,  what is the Displacement_threshold_pixels mean?

bar@foo:~/VideoStabilization$ python3 src/preproc.py <video_file_path>
bar@foo:~/VideoStabilization$ python3 src/stabilize.py <Displacement_threshold_pixels>
bar@foo:~/VideoStabilization$ python3 src/generate.py <video_file_path> <Displacement_threshold_pixels>

**Comment by itsagoodbrain** [comment]
It's an integer input not a file. See the closed issues for more information regarding values.
