### ISSUE TITLE
Setting Dispacement_threshold_pixels.

### ISSUE THREAD

**Issue by HyeongminLEE** [VAIBHAV-2303/VideoStabilization#4]
Hi, thank you for sharing a good project. How did you set Dispacement_threshold_pixels value in your case?

**Comment by VAIBHAV-2303** [comment]
Apologies for replying late. The Dispacement_threshold_pixels parameter value really depends on the user's requirements and the video itself. A very large value might result in very small output frame and a very large value might not lead to a decent enough stabilization.
