### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'transforms.pkl'

### ISSUE THREAD

**Issue by ctrlbrk42** [VAIBHAV-2303/VideoStabilization#5]
# ./script.sh GX020111-_-OWBVWMv95egPo.MP4 500
Preprocessing
[ WARN:0@0.086] global /io/opencv_contrib/modules/xfeatures2d/misc/python/shadow_sift.hpp (13) SIFT_create DEPRECATED: cv.xfeatures2d.SIFT_create() is deprecated due SIFT tranfer to the main repository. https://github.com/opencv/opencv/issues/16736
0.003121098626716604% completed
./script.sh: line 2:  9377 Killed                  python3 src/preproc.py $1
Optimizing trajectory
Traceback (most recent call last):
  File "/root/VideoStabilization/src/stabilize.py", line 9, in <module>
    with open('transforms.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transforms.pkl'
Generating output
Traceback (most recent call last):
  File "/root/VideoStabilization/src/generate.py", line 19, in <module>
    with open('transforms.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transforms.pkl'
06:26 PM [echelon]~/VideoStabilization root # python3 --version
Python 3.9.2

**Comment by VAIBHAV-2303** [comment]
For some reason your python3 process was killed and the file transforms.pkl never got generated resulting into the above error. Did you try running again?
